[global]

UIName = Salcols Community Edition
Description = The Salcols Community Edition project, developed by the Salcols Community.
DllName = WXPMod
;; DllName = WXPMod_DCMod
Playable = 1
ModFolder = Salcol_CE
ModVersion = version 3.22
TextureFE = Art/UI/Textures/Title_winter_assault.tga
TextureIcon =

DataFolder.1 = Data\Art
DataFolder.2 = Data
DataFolder.3 = Data\Ai
DataFolder.4 = Data\Scenarios

ArchiveFile.1 = DataSalcolArt
ArchiveFile.2 = DataSalcol
ArchiveFile.3 = DataSalcolAI
ArchiveFile.4 = DataSalcolScenarios

RequiredMod.1 = DXP2
RequiredMod.2 = W40k



